version: '3.4'

services:
  flowermarket.web.api:
    links:  
      - sqlserver
      - mongo.db
    image: ${DOCKER_REGISTRY-}flowermarketwebapi
    build:
      context: .
      dockerfile: FlowerMarket.Web.Api/Dockerfile
  sqlserver:  
    image: microsoft/mssql-server-linux:2017-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "BigPassw0rd"
    volumes:
      - ./data/mssql:/var/opt/mssql3
    ports:
      - '1434:1433'
    expose:
      - 1433
  mongo.db:
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "myBigDevPassword!"
      MONGO_INITDB_DATABASE: "LogDatabase"
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27018:27017"